server:
  port: 9091
spring:
  application:
    name: server-private
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8081/eureka


    fetch-registry: true
    register-with-eureka: true